name: Build Debug APK

on:
  push:
    branches:
      - main
      - feature/add_stun
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build debug APK
        run: ./gradlew assembleGithubDebug --no-configuration-cache

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: plain-app-debug
          path: app/build/outputs/apk/github/debug/*.apk
          retention-days: 7